services:

# ----------- real time data ----------------#

  # zookeeper is necessary to manage Kafka metadata
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181 #kafka itself
      ZOOKEEPER_TICK_TIME: 2000 # default heartbeat setting
    ports:
      - "2181:2181"
    restart: unless-stopped

  # kafka is needed to manage the datastream
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 # this is for local development
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://159.65.41.22:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped

# ----------- data storage ----------------#

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123" #HTTP interface
      - "9000:9000" # native interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: mysecurepassword
    restart: unless-stopped

# ----------- visualization ----------------#

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: grafana-clickhouse-datasource
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_SECURITY_ALLOW_EMBEDDING: "true"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

# ----------- monitoring ----------------#

# checks if services (like health) are up
  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox
    ports:
      - "9115:9115"
    command:
      - "--config.file=/etc/blackbox/blackbox.yml"
    volumes:
      - ./blackbox.yml:/etc/blackbox/blackbox.yml
    restart: unless-stopped

# scrapes endpoints for metrics/alerts. the central "brain"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped


# ----------- logs ----------------#

# collects all logs and ships to loki
  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    volumes:
      - ./log_data:/var/log/pipeline:ro
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    restart: unless-stopped

# aggregates all logs
  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    restart: unless-stopped

# ----------- code ----------------#
  pipeline:
    build: .
    container_name: pipeline
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - kafka
      - clickhouse
    volumes:
      - ./log_data:/app/log_data
    restart: unless-stopped
    stop_grace_period: 20s

volumes:
  clickhouse_data:
  grafana-data:
